name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:gh-pages

      - name: Deploy
        run: |
          # Remove existing docs directory if it exists
          rm -rf docs
          
          # Create docs directory and copy build files
          mkdir -p docs
          cp -r dist/* docs/
          
          # Configure git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Add and commit changes
          git add docs
          git status
          git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
          
          # Push changes
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" || echo "No changes to push"

      - name: Verify deployment
        run: |
          echo "Waiting for deployment to complete..."
          sleep 30
          curl -f https://kondo-masaki.github.io/backlog-attachment-cleaner-v2/ || echo "Deployment verification failed" 